version: '3.8'

services:
  # 1. СУБД PostgreSQL
  # postgres:
  #   image: postgres:16-alpine
  #   container_name: locomotive_postgres
  #   environment:
  #     POSTGRES_DB: locomotive_db
  #     POSTGRES_USER: dev_user
  #     POSTGRES_PASSWORD: dev_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data_v2:/var/lib/postgresql/data
  #   networks:
  #     - locomotive_network
  #   restart: unless-stopped

  # 2. Бэкенд-оркестратор (Spring Boot)
  backend:
    build:
      context: ./backend # Путь к подпапке с бэкендом
      dockerfile: Dockerfile
    container_name: locomotive_backend
    ports:
      - "8120:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/locomotive_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DOCKER_COMPOSE_ENABLED: "false"
      APP_ML_MOCK_ENABLED: "false"
      # Адрес FastAPI-сервиса с новым портом 8045
      APP_ML_SERVICE_URL: "http://fastapi:8045" 
    networks:
      - locomotive_network
    restart: unless-stopped

  # # 3. vLLM-сервер (ИИ-движок, переведенный на стабильную версию v0.6.0)
  # vllm:
  #   image: vllm/vllm-openai:v0.6.0 # Переключились на версию v0.6.0
  #   container_name: vllm-server
  #   command: >
  #     --model baidu/Qianfan-OCR
  #     --device cpu
  #     --host 0.0.0.0
  #     --port 8000
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - VLLM_TARGET_DEVICE=cpu
  #   volumes:
  #     - ~/.cache/huggingface:/root/.cache/huggingface
  #   networks:
  #     - locomotive_network
  #   restart: unless-stopped

  # 4. FastAPI-сервер (Аналитический модуль)
  fastapi:
    build:
      context: ./ml_service # Контекст сборки — папка ml_service, так как Dockerfile.fastapi и requirements.txt лежат там
      dockerfile: Dockerfile.fastapi
    container_name: fastapi-server
    ports:
      - "8045:8045"  # Проброс порта наружу
    environment:
      - DEVICE=cpu
      - MODEL_NAME=baidu/Qianfan-OCR
      - MOCK_MODE=true  # Включает режим мокового общения с нейронкой
      - FASTAPI_PORT=8045
      - PYTHONUNBUFFERED=1
    # Команда запуска uvicorn указывает на модуль app.main внутри скопированной директории
    command: uvicorn app.main:app --host 0.0.0.0 --port 8045
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    networks:
      - locomotive_network
    restart: unless-stopped

  # 5. Фронтенд (React + Nginx)
  frontend:
    build:
      context: ./frontend/rzd-incidents 
      dockerfile: Dockerfile
    container_name: locomotive_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - locomotive_network
    restart: unless-stopped

volumes:
  postgres_data_v2:

networks:
  locomotive_network:
    driver: bridge
