FROM python:3.11-slim

# Системные зависимости
RUN apt-get update && apt-get install -y \
    poppler-utils \
    libreoffice \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Шаг 1. Клонируем репозиторий с кодом модели на этапе сборки образа
RUN git clone -b develop --single-branch https://github.com/baidubce/skills.git /tmp/skills && \
    cp -r /tmp/skills/skills/qianfanocr-document-intelligence/* /app/ && \
    rm -rf /tmp/skills

# Шаг 2. Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir torch==2.5.1 torchvision==0.20.1 --index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir -r requirements.txt

# Шаг 3. Копируем исходный код нашего приложения (файлы приложения перезапишут только себя)
COPY . .

CMD ["python", "app/main.py"]