version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi-server
    ports:
      - "8001:8001"
    environment:
      - MODEL_NAME=baidu/Qianfan-OCR
      - CUDA_VISIBLE_DEVICES=0   # если нужна GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]   # опционально
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped